import axios from "axios";
import Head from "next/head";
import { Button, Card } from "react-bootstrap";

import styleProducts from "@/styles/Products.module.css";
import Link from "next/link";

export default function singleProduct({ product }) {
  const { category, title, price, image, id } = product;
  return (
    <>
      <Head>
        <title>{title} Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className={styleProducts.cards_pro}>
          <Card className={styleProducts.card} key={id}>
            <Card.Img
              className={styleProducts.cardImg}
              variant="top"
              src={image}
            />
            <Card.Body>
              <Card.Title className="title_card">{category}</Card.Title>
              <Card.Text>{price} $</Card.Text>
              <Button>
                <Link href="/cart">Add To cart</Link>
              </Button>
            </Card.Body>
          </Card>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const res = await axios.get(
    `https://fakestoreapi.com/products/${context.query.id}`
  );
  console.log(res.data);

  return {
    props: { product: res.data },
  };
}
