import axios from "axios";
import Head from "next/head";

export default function postId({ post }) {
  return (
    <>
      <Head>
        <title>postId Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div key={post.id}>
          <span> {post.id}</span>
          <p> {post.title}</p>
          <h1> {post.description}</h1>
          <h1> {post.category}</h1>
          <img
            className="img-img"
            src={post.image}
            classNameName="post-img"
            alt={post.title}
          />
          <hr />
        </div>
      </>
    </>
  );
}

export async function getServerSideProps(context) {
  const res = await axios.get(
    `https://fakestoreapi.com/products/${context.query.postId}`
  );
  console.log(res.data);

  return {
    props: { post: res.data },
  };
}
