import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import { Container } from "react-bootstrap";

// import Image from "next/image";
import { Inter } from "@next/font/google";
import Products from "../pages/products/index";
import Sin_up from "@/components/Sin_up";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Next App</title>
        <link rel="icon" href="/ctp1.png" />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="">
        <Container>
          <h1>Home Page</h1>
          {/* <div className="content_card col-3 d-flex">
          {products.map((product) => (
            <Products key={product.id} product={product} />
          ))}
        </div> */}
        </Container>
      </div>
    </>
  );
}

// export async function getStaticProps() {
//   const req = await fetch("https://fakestoreapi.com/products");
//   const products = await req.json();

//   return {
//     props: { products },
//   };
// }
